//
//  CreateOrderInteractor.swift
//  CleanStore
//
//  Created by Andrew Napier on 29/11/18.
//  Copyright (c) 2018 Andrew Napier. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateOrderBusinessLogic
{
    func doSomething(request: CreateOrder.Something.Request)
    var shippingMethods: [String] { get }
    func formatExpirationDate(request: CreateOrder.FormatExpirationDate.Request)
}

protocol CreateOrderDataStore
{
    //var name: String { get set }
}

class CreateOrderInteractor: CreateOrderBusinessLogic, CreateOrderDataStore
{
    func formatExpirationDate(request: CreateOrder.FormatExpirationDate.Request) {
        let response = CreateOrder.FormatExpirationDate.Response(date: request.date)
        presenter?.presentExpirationDate(response: response)
    }
    
    var shippingMethods: [String] = [
        "Standard Shipping",
        "Two-Day Shipping ",
        "One-Day Shipping "]
    
    var presenter: CreateOrderPresentationLogic?
    var worker: CreateOrderWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: CreateOrder.Something.Request)
    {
        worker = CreateOrderWorker()
        worker?.doSomeWork()
        
        let response = CreateOrder.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
